version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/my-app   # Destination on EC2

hooks:
  BeforeInstall:
    - runas: ec2-user
      commands:
        # Stop any existing app process using pm2
        - pm2 stop my-app || true

  AfterInstall:
    - runas: ec2-user
      commands:
        # Navigate to app folder
        - cd /var/www/my-app
        # Install Node.js dependencies
        - npm install

  ApplicationStart:
    - runas: ec2-user
      commands:
        - cd /var/www/my-app
        # Start app using PM2
        - pm2 start index.js --name my-app
        # Save PM2 process to restart on reboot
        - pm2 save
        - pm2 startup systemd -u ec2-user --hp /home/ec2-user

  ValidateService:
    - runas: ec2-user
      commands:
        # Health check for ELB
        - if curl -s http://localhost:3000/ >/dev/null; then echo "Health check passed"; else echo "Health check failed"; exit 1; fi
